[tool.poetry]
name = "FalkorDB"
version = "1.2.0"
description = "Python client for interacting with FalkorDB database"
authors = ["FalkorDB inc <info@falkordb.com>"]

readme = "README.md"
repository = "http://github.com/falkorDB/falkordb-py"
homepage = "http://falkordb-py.readthedocs.io"
keywords = ['FalkorDB', 'GraphDB', 'Cypher']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

packages = [{include = "falkordb"}]

[tool.poetry.dependencies]
python = "^3.9"
redis = ">=7.0.0,<8.0.0"
python-dateutil = "^2.9.0"

[tool.poetry.group.test.dependencies]
pytest-cov = ">=4.1,<6.0"
pytest = "8.3.5"
pytest-asyncio = ">=0.23.4,<0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
